//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelwebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Code_reserv { get; set; }
        public Nullable<int> Code_r { get; set; }
        public Nullable<int> Code_m { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Member Member { get; set; }
    }
}
